@baseURL = https://pure-lowlands-40590.herokuapp.com/api/persons
@URL = http://localhost:3001/api/persons

POST {{URL}} HTTP/1.1
Content-Type: application/json

{
	"name": "Police",
	"number": "111"
}
###
GET {{URL}}/102490124
###
GET {{URL}}/61c43a7fb6c8394614aa8acd
###
GET {{URL}}

###
PUT {{URL}}/61c444a40f99a27566ff5785
Content-Type: application/json

{
	"name": "Joe",
	"number": "12345"
}

###
DELETE {{URL}}/61c43a7fb6c8394614aa8acd

